server {
    listen 80;
    server_name phpfpm.local;

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    index index.php index.html;

    root /var/www/php;
    autoindex off;

    error_page 403 /error/403.php;
    error_page 404 /error/404.php;
    error_page 405 /error/405.php;
    error_page 500 /error/500.php;

    location /error/ {
        try_files $uri =404;
        include fpm_pass.conf;
    }

    location /api/ {
        try_files $uri.php =404;
        include fpm_pass.conf;

        fastcgi_intercept_errors off;
        default_type application/json;

        location = /api/prelude {
            return 403;
        }
    }

    location /app/ {
        location ~ \.php$ {
            try_files $uri =404;
            include fpm_pass.conf;
        }

        location = /app/prelude.php {
            return 403;
        }
    }
    
    location /static/ {
        try_files $uri =404;
    }

    location /wss/ {
        proxy_pass http://wss:8888/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location = / {
        return 301 /app/index.php;
    }

    location / {
        deny all;
    }
}
