DROP TABLE IF EXISTS PrgPosts;
DROP TABLE IF EXISTS PrgIssues;
DROP TABLE IF EXISTS PrgEvaluations;
DROP TABLE IF EXISTS PrgFiles;
DROP TABLE IF EXISTS PrgCategories;
DROP TABLE IF EXISTS PrgCollaborators;
DROP TABLE IF EXISTS PrgRevisions;
DROP TABLE IF EXISTS PrgPermissions;
DROP TABLE IF EXISTS PrgProjects;
DROP TABLE IF EXISTS PrgNotifications;
DROP TABLE IF EXISTS PrgUsers;
 