DROP TABLE IF EXISTS PrgPost;
DROP TABLE IF EXISTS PrgProblemi;
DROP TABLE IF EXISTS PrgValutazioni;
DROP TABLE IF EXISTS PrgFile;
DROP TABLE IF EXISTS PrgCategorie;
DROP TABLE IF EXISTS PrgCollaboratori;
DROP TABLE IF EXISTS PrgRevisioni;
DROP TABLE IF EXISTS PrgPermessi;
DROP TABLE IF EXISTS PrgProgetti;
DROP TABLE IF EXISTS PrgNotifiche;
DROP TABLE IF EXISTS PrgUtenti;
 